
#publish all joint states ------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

#position Controllers
joint_1_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_1
  pid: {p: 10.0 , i: 1 , d: 0.1 }
joint_2_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_2
  pid: {p: 10.0 , i: 1 , d: 0.1 }
joint_3_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_3
  pid: {p: 10.0 , i: 1 , d: 0.1 }
joint_4_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_4
  pid: {p: 10.0 , i: 1 , d: 0.1 }
joint_5_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_5
  pid: {p: 10.0 , i: 1 , d: 0.1 }
grip_1_position_controller:
  type: effort_controllers/JointPositionController
  joint: grip_1
  pid: {p: 10.0 , i: 1 , d: 0.1 }
grip_2_position_controller:
  type: effort_controllers/JointPositionController
  joint: grip_2
  pid: {p: 10.0 , i: 1 , d: 0.1 }